### ISSUE TITLE
Spike - Nether travel using train

### ISSUE THREAD

**Issue by Keruj47** [Keruj47/Nomad-Train#3]
Nether travel using train check

**Comment by Keruj47** [comment]
In the Nether worldborder size stays more or less the same, but the worldborder moves too slow (possibly multiply the coordinates by 8 when in the Nether?)

**Comment by Mkomko7** [comment]
> In the Nether worldborder size stays more or less the same, but the worldborder moves too slow (possibly multiply the coordinates by 8 when in the Nether?)

You mean multiply size of world border by some value? This way it won't be too quickly reached by the train

**Comment by Keruj47** [comment]
> > In the Nether worldborder size stays more or less the same, but the worldborder moves too slow (possibly multiply the coordinates by 8 when in the Nether?)
> 
> You mean multiply size of world border by some value? This way it won't be too quickly reached by the train

Multiply center position coordinates by 8

**Comment by Keruj47** [comment]
Research done
Travel in the Nether is possible
Prototype created
